"use strict";(self.webpackChunkgpupdate_docs=self.webpackChunkgpupdate_docs||[]).push([[9382],{2475:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>h,contentTitle:()=>c,default:()=>l,frontMatter:()=>o,metadata:()=>r,toc:()=>a});var i=n(4848),s=n(8453);const o={},c=void 0,r={id:"gpoa/util/exceptions",title:"exceptions",description:"FunctionDef geterr",source:"@site/docs/gpoa/util/exceptions.md",sourceDirName:"gpoa/util",slug:"/gpoa/util/exceptions",permalink:"/gpupdate-docs/docs/gpoa/util/exceptions",draft:!1,unlisted:!1,tags:[],version:"current",frontMatter:{},sidebar:"defaultSidebar",previous:{title:"dbus",permalink:"/gpupdate-docs/docs/gpoa/util/dbus"},next:{title:"gpoa_ini_parsing",permalink:"/gpupdate-docs/docs/gpoa/util/gpoa_ini_parsing"}},h={},a=[{value:"FunctionDef geterr",id:"functiondef-geterr",level:2},{value:"ClassDef NotUNCPathError",id:"classdef-notuncpatherror",level:2},{value:"FunctionDef <strong>init</strong>(self, path)",id:"functiondef-initself-path",level:3},{value:"FunctionDef <strong>str</strong>(self)",id:"functiondef-strself",level:3},{value:"ClassDef GetGPOListFail",id:"classdef-getgpolistfail",level:2},{value:"FunctionDef <strong>init</strong>(self, exc)",id:"functiondef-initself-exc",level:3},{value:"FunctionDef <strong>str</strong>(self)",id:"functiondef-strself-1",level:3}];function d(e){const t={code:"code",h2:"h2",h3:"h3",hr:"hr",li:"li",ol:"ol",p:"p",pre:"pre",strong:"strong",ul:"ul",...(0,s.R)(),...e.components};return(0,i.jsxs)(i.Fragment,{children:[(0,i.jsx)(t.h2,{id:"functiondef-geterr",children:"FunctionDef geterr"}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"geterr"}),": The function of geterr is to fetch information about recent exceptions that occurred in the program. This information can be used to print tracebacks and other relevant details in a consistent manner."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Parameters"}),": This function does not take any parameters."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":"]}),"\n",(0,i.jsxs)(t.ol,{children:["\n",(0,i.jsxs)(t.li,{children:["\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.code,{children:"etype, evalue, etrace = sys.exc_info()"}),": This line retrieves information about the most recent exception that occurred in the program using the ",(0,i.jsx)(t.code,{children:"sys.exc_info()"})," function. The function returns a tuple containing three elements: the exception type, the exception value, and the traceback object. These elements are unpacked into the variables ",(0,i.jsx)(t.code,{children:"etype"}),", ",(0,i.jsx)(t.code,{children:"evalue"}),", and ",(0,i.jsx)(t.code,{children:"etrace"}),"."]}),"\n"]}),"\n",(0,i.jsxs)(t.li,{children:["\n",(0,i.jsxs)(t.p,{children:["The next block of code creates a dictionary called ",(0,i.jsx)(t.code,{children:"traceinfo"})," that stores various details about the exception. These details include:"]}),"\n",(0,i.jsxs)(t.ul,{children:["\n",(0,i.jsxs)(t.li,{children:[(0,i.jsx)(t.code,{children:"'file'"}),": The name of the Python file where the exception occurred."]}),"\n",(0,i.jsxs)(t.li,{children:[(0,i.jsx)(t.code,{children:"'line'"}),": The line number in the file where the exception occurred."]}),"\n",(0,i.jsxs)(t.li,{children:[(0,i.jsx)(t.code,{children:"'name'"}),": The name of the function or method where the exception occurred."]}),"\n",(0,i.jsxs)(t.li,{children:[(0,i.jsx)(t.code,{children:"'type'"}),": The type of exception that occurred."]}),"\n",(0,i.jsxs)(t.li,{children:[(0,i.jsx)(t.code,{children:"'message'"}),": The error message associated with the exception."]}),"\n"]}),"\n"]}),"\n",(0,i.jsxs)(t.li,{children:["\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.code,{children:"del(etype, evalue, etrace)"}),": This line deletes the variables ",(0,i.jsx)(t.code,{children:"etype"}),", ",(0,i.jsx)(t.code,{children:"evalue"}),", and ",(0,i.jsx)(t.code,{children:"etrace"})," to free up memory, as they are no longer needed after the ",(0,i.jsx)(t.code,{children:"traceinfo"})," dictionary has been created."]}),"\n"]}),"\n",(0,i.jsxs)(t.li,{children:["\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.code,{children:"return traceinfo"}),": Finally, the function returns the ",(0,i.jsx)(t.code,{children:"traceinfo"})," dictionary, which contains all the relevant information about the most recent exception that occurred in the program."]}),"\n"]}),"\n"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":"]}),"\n",(0,i.jsxs)(t.ul,{children:["\n",(0,i.jsx)(t.li,{children:"This function should be called immediately after an exception has occurred in the program to ensure that it captures accurate and relevant information about the exception."}),"\n",(0,i.jsxs)(t.li,{children:["The function does not handle the exception itself; it only gathers information about it. To handle the exception, you should use a ",(0,i.jsx)(t.code,{children:"try"}),"/",(0,i.jsx)(t.code,{children:"except"})," block in your code."]}),"\n"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Output Example"}),":"]}),"\n",(0,i.jsxs)(t.p,{children:["Here's an example of what the output of the ",(0,i.jsx)(t.code,{children:"geterr()"})," function might look like:"]}),"\n",(0,i.jsx)(t.pre,{children:(0,i.jsx)(t.code,{className:"language-python",children:"{\n    'file': '/path/to/my/program.py',\n    'line': 17,\n    'name': 'my_function',\n    'type': 'ZeroDivisionError',\n    'message': 'division by zero'\n}\n"})}),"\n",(0,i.jsxs)(t.p,{children:["In this example, the function returned a dictionary containing information about a ",(0,i.jsx)(t.code,{children:"ZeroDivisionError"})," that occurred in the ",(0,i.jsx)(t.code,{children:"my_function"})," function in the ",(0,i.jsx)(t.code,{children:"program.py"}),' file on line 17. The error message was "division by zero".']}),"\n",(0,i.jsx)(t.h2,{id:"classdef-notuncpatherror",children:"ClassDef NotUNCPathError"}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"NotUNCPathError"}),": The function of NotUNCPathError is to raise an exception when the provided path is not a UNC path."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"attributes"}),":\n\xb7 path: The path that was provided and determined not to be a UNC path."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":\nThe ",(0,i.jsx)(t.code,{children:"NotUNCPathError"})," class is derived from the built-in ",(0,i.jsx)(t.code,{children:"Exception"})," class and is used to indicate that a provided path is not a UNC path. The class has a single attribute, ",(0,i.jsx)(t.code,{children:"path"}),", which holds the path that was determined not to be a UNC path."]}),"\n",(0,i.jsxs)(t.p,{children:["The ",(0,i.jsx)(t.code,{children:"__init__"})," method takes a single parameter, ",(0,i.jsx)(t.code,{children:"path"}),", which is the path to be checked. The method sets the ",(0,i.jsx)(t.code,{children:"path"})," attribute to the provided path and then checks if the path is a UNC path. If the path is not a UNC path, the method raises a ",(0,i.jsx)(t.code,{children:"NotUNCPathError"})," with the provided path as the argument."]}),"\n",(0,i.jsxs)(t.p,{children:["This class is used in the ",(0,i.jsx)(t.code,{children:"UNCPath"})," class in the ",(0,i.jsx)(t.code,{children:"paths.py"})," module to ensure that the provided path is a UNC path. If the path is not a UNC path, a ",(0,i.jsx)(t.code,{children:"NotUNCPathError"})," is raised."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":\nThis class should be used to check if a path is a UNC path before performing any operations that require a UNC path. Failing to check for a UNC path can result in unexpected behavior or errors."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Output Example"}),":"]}),"\n",(0,i.jsx)(t.pre,{children:(0,i.jsx)(t.code,{className:"language-python",children:"try:\n    unc_path = UNCPath('C:\\\\temp\\\\file.txt')\nexcept NotUNCPathError as exc:\n    print(f'The path {exc.path} is not a UNC path.')\n"})}),"\n",(0,i.jsx)(t.p,{children:"Output:"}),"\n",(0,i.jsx)(t.pre,{children:(0,i.jsx)(t.code,{className:"language-python",children:"The path C:\\temp\\file.txt is not a UNC path.\n"})}),"\n",(0,i.jsxs)(t.h3,{id:"functiondef-initself-path",children:["FunctionDef ",(0,i.jsx)(t.strong,{children:"init"}),"(self, path)"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:(0,i.jsx)(t.code,{children:"__init__"})}),": The function of ",(0,i.jsx)(t.code,{children:"__init__"})," is to initialize the NotUNCPathError object with a given path."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"parameters"}),":\n\xb7 ",(0,i.jsx)(t.code,{children:"path"}),": The path that will be assigned to the NotUNCPathError object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":\nThe ",(0,i.jsx)(t.code,{children:"__init__"})," function is a special method in Python classes, called when an object is initialized. In this case, it is defining the behavior when a new NotUNCPathError object is created."]}),"\n",(0,i.jsxs)(t.p,{children:["The function takes one argument, ",(0,i.jsx)(t.code,{children:"path"}),", which is the path that will be assigned to the NotUNCPathError object. This argument is then assigned to the ",(0,i.jsx)(t.code,{children:"path"})," attribute of the object using the ",(0,i.jsx)(t.code,{children:"self.path = path"})," syntax."]}),"\n",(0,i.jsx)(t.p,{children:"Here's an example of how this function might be used:"}),"\n",(0,i.jsx)(t.pre,{children:(0,i.jsx)(t.code,{className:"language-python",children:"error = NotUNCPathError('C:\\my_directory')\n"})}),"\n",(0,i.jsx)(t.p,{children:"In this example, a new NotUNCPathError object is created and initialized with the path 'C:\\my_directory'."}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":\nThe NotUNCPathError class is likely a custom exception class that is used to raise an exception when a UNC path is not provided. Therefore, it is important to ensure that the path being passed to the ",(0,i.jsx)(t.code,{children:"__init__"})," function is not a UNC path. If it is, a ",(0,i.jsx)(t.code,{children:"NotUNCPathError"})," exception should be raised."]}),"\n",(0,i.jsxs)(t.p,{children:["Additionally, it is important to note that the ",(0,i.jsx)(t.code,{children:"self"})," parameter is not explicitly passed when calling the ",(0,i.jsx)(t.code,{children:"__init__"})," function. Instead, it is automatically passed as a reference to the newly created object."]}),"\n",(0,i.jsx)(t.hr,{}),"\n",(0,i.jsxs)(t.h3,{id:"functiondef-strself",children:["FunctionDef ",(0,i.jsx)(t.strong,{children:"str"}),"(self)"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:(0,i.jsx)(t.code,{children:"__str__"})}),": The function of ",(0,i.jsx)(t.code,{children:"__str__"})," is to return a human-readable string representation of the NotUNCPathError object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"parameters"}),": This function does not take any parameters."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":\nThe ",(0,i.jsx)(t.code,{children:"__str__"})," function is a special method in Python that is called when the ",(0,i.jsx)(t.code,{children:"str()"})," function is called on an object or when the object is implicitly converted to a string, such as when it is printed. In this case, the ",(0,i.jsx)(t.code,{children:"__str__"})," function returns the value of the ",(0,i.jsx)(t.code,{children:"path"})," attribute of the NotUNCPathError object."]}),"\n",(0,i.jsxs)(t.p,{children:["The ",(0,i.jsx)(t.code,{children:"self"})," parameter is a reference to the current instance of the object, and it is used to access the ",(0,i.jsx)(t.code,{children:"path"})," attribute of the object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":"]}),"\n",(0,i.jsxs)(t.ul,{children:["\n",(0,i.jsxs)(t.li,{children:["The ",(0,i.jsx)(t.code,{children:"__str__"})," function should return a string that is suitable for representing the object in a human-readable format."]}),"\n",(0,i.jsxs)(t.li,{children:["It is important to note that the ",(0,i.jsx)(t.code,{children:"__str__"})," function should not be used for converting an object to a string for programmatic use. Instead, the ",(0,i.jsx)(t.code,{children:"__repr__"})," function should be used for this purpose."]}),"\n",(0,i.jsxs)(t.li,{children:["The ",(0,i.jsx)(t.code,{children:"__str__"})," function is often used in conjunction with the ",(0,i.jsx)(t.code,{children:"print()"})," function to display information about an object."]}),"\n"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Output Example"}),":"]}),"\n",(0,i.jsxs)(t.p,{children:['If a NotUNCPathError object is created with the path attribute set to "C:\\Users\\Username\\Documents", then calling the ',(0,i.jsx)(t.code,{children:"str()"})," function on the object would return the following string:"]}),"\n",(0,i.jsx)(t.pre,{children:(0,i.jsx)(t.code,{children:'"C:\\\\Users\\\\Username\\\\Documents"\n'})}),"\n",(0,i.jsxs)(t.p,{children:["It is important to note that the string returned by the ",(0,i.jsx)(t.code,{children:"__str__"})," function may differ from the actual path stored in the object, as it may be formatted in a way that is easier for humans to read."]}),"\n",(0,i.jsx)(t.hr,{}),"\n",(0,i.jsx)(t.h2,{id:"classdef-getgpolistfail",children:"ClassDef GetGPOListFail"}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"GetGPOListFail"}),": The function of GetGPOListFail is to manage and raise exceptions that occur during the process of getting GPO (Group Policy Object) list in the ",(0,i.jsx)(t.code,{children:"gpoa"})," project."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"attributes"}),":\n\xb7 exc: This attribute holds the exception object that is caught during the execution of the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function in the ",(0,i.jsx)(t.code,{children:"smbcreds"})," module of the ",(0,i.jsx)(t.code,{children:"windows.py"})," file."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":\nThe ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," class is derived from the built-in ",(0,i.jsx)(t.code,{children:"Exception"})," class, which enables it to handle and raise exceptions. The ",(0,i.jsx)(t.code,{children:"__init__"})," method takes a single parameter ",(0,i.jsx)(t.code,{children:"exc"}),", which is the exception object that is caught during the execution of the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function. The ",(0,i.jsx)(t.code,{children:"__str__"})," method returns the exception message as a string, which is useful for debugging and logging purposes."]}),"\n",(0,i.jsxs)(t.p,{children:["The ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," class is used in the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function of the ",(0,i.jsx)(t.code,{children:"smbcreds"})," module in the ",(0,i.jsx)(t.code,{children:"windows.py"})," file. When an exception occurs during the execution of the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function, it raises a ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception with the caught exception object as its parameter. This allows the calling function to handle the exception in a more specific way, rather than just catching the base ",(0,i.jsx)(t.code,{children:"Exception"})," class."]}),"\n",(0,i.jsxs)(t.p,{children:["In the ",(0,i.jsx)(t.code,{children:"update_gpos"})," function of the ",(0,i.jsx)(t.code,{children:"smbcreds"})," module in the ",(0,i.jsx)(t.code,{children:"windows.py"})," file, the ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception is caught and handled by changing the selected domain controller (DC) and retrying the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function. This is useful in scenarios where the exception is caused by a temporary issue with the selected DC."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":"]}),"\n",(0,i.jsxs)(t.ul,{children:["\n",(0,i.jsxs)(t.li,{children:["The ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," class should only be used to handle exceptions that occur during the execution of the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function."]}),"\n",(0,i.jsxs)(t.li,{children:["When raising a ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception, it is important to pass the caught exception object as its parameter, to allow the calling function to handle the exception in a specific way."]}),"\n"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Output Example"}),":\nWhen an exception occurs during the execution of the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function, a ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception is raised with the caught exception object as its parameter. For example, if a ",(0,i.jsx)(t.code,{children:"samba.SambaHTTPError"})," exception occurs, a ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception is raised with the ",(0,i.jsx)(t.code,{children:"samba.SambaHTTPError"})," object as its parameter. The calling function can then handle the ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," exception in a specific way, such as changing the selected DC and retrying the ",(0,i.jsx)(t.code,{children:"get_gpos"})," function."]}),"\n",(0,i.jsxs)(t.h3,{id:"functiondef-initself-exc",children:["FunctionDef ",(0,i.jsx)(t.strong,{children:"init"}),"(self, exc)"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:(0,i.jsx)(t.code,{children:"__init__"})}),": The function of ",(0,i.jsx)(t.code,{children:"__init__"})," is to initialize the GetGPOListFail object with an exception object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"parameters"}),":\n\xb7 ",(0,i.jsx)(t.code,{children:"exc"}),": The exception object to be stored in the GetGPOListFail object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),":\nThe ",(0,i.jsx)(t.code,{children:"__init__"})," function is a special method in Python classes, called when an object is initialized. In this case, it is used to initialize the GetGPOListFail object with an exception object."]}),"\n",(0,i.jsxs)(t.p,{children:["The ",(0,i.jsx)(t.code,{children:"exc"})," parameter is the exception object that will be stored in the GetGPOListFail object. This object can then be used for further error handling or logging."]}),"\n",(0,i.jsxs)(t.p,{children:["The ",(0,i.jsx)(t.code,{children:"self"})," parameter is a reference to the current instance of the class and is used to access variables and methods associated with that instance."]}),"\n",(0,i.jsxs)(t.p,{children:["In the body of the function, the ",(0,i.jsx)(t.code,{children:"exc"})," parameter is assigned to the ",(0,i.jsx)(t.code,{children:"exc"})," attribute of the ",(0,i.jsx)(t.code,{children:"self"})," object. This creates a new attribute in the GetGPOListFail object, which can be accessed later."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),":\nIt is important to note that the ",(0,i.jsx)(t.code,{children:"exc"})," parameter should be an exception object, otherwise, it will raise a TypeError. Also, the ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," class should be used as a base class for custom exceptions that occur when getting a list of Group Policy Objects (GPOs). This class can be used to provide more specific information about the error, making it easier to diagnose and fix."]}),"\n",(0,i.jsx)(t.hr,{}),"\n",(0,i.jsxs)(t.h3,{id:"functiondef-strself-1",children:["FunctionDef ",(0,i.jsx)(t.strong,{children:"str"}),"(self)"]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:(0,i.jsx)(t.code,{children:"__str__"})}),": The function of ",(0,i.jsx)(t.code,{children:"__str__"})," is to return a human-readable string representation of an object."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"parameters"}),": This function does not take any parameters."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Code Description"}),": The ",(0,i.jsx)(t.code,{children:"__str__"})," function is a special method in Python that is called when the ",(0,i.jsx)(t.code,{children:"str()"})," function is called on an object, or when the object is implicitly converted to a string using the ",(0,i.jsx)(t.code,{children:"print()"})," function. In this case, the function returns the value of the ",(0,i.jsx)(t.code,{children:"exc"})," attribute of the object. The ",(0,i.jsx)(t.code,{children:"exc"})," attribute is expected to be a string, as it is being returned directly by the ",(0,i.jsx)(t.code,{children:"__str__"})," method."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Note"}),": The ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," class, which this ",(0,i.jsx)(t.code,{children:"__str__"})," method is a part of, is likely a custom exception class that is used to indicate failure in obtaining a list of Group Policy Objects (GPOs). When such a failure occurs, an instance of this class is created and can be caught by a ",(0,i.jsx)(t.code,{children:"try"}),"/",(0,i.jsx)(t.code,{children:"except"})," block. By providing a custom ",(0,i.jsx)(t.code,{children:"__str__"})," method, the error message that is displayed when this exception is caught can be customized to provide more meaningful information to the developer or user."]}),"\n",(0,i.jsxs)(t.p,{children:[(0,i.jsx)(t.strong,{children:"Output Example"}),": If an instance of ",(0,i.jsx)(t.code,{children:"GetGPOListFail"})," was created with the ",(0,i.jsx)(t.code,{children:"exc"})," attribute set to ",(0,i.jsx)(t.code,{children:"'Failed to connect to the domain controller'"}),", calling ",(0,i.jsx)(t.code,{children:"str()"})," on that instance would return the string ",(0,i.jsx)(t.code,{children:"'Failed to connect to the domain controller'"}),". Similarly, printing that instance would also produce the same output."]}),"\n",(0,i.jsx)(t.hr,{})]})}function l(e={}){const{wrapper:t}={...(0,s.R)(),...e.components};return t?(0,i.jsx)(t,{...e,children:(0,i.jsx)(d,{...e})}):d(e)}},8453:(e,t,n)=>{n.d(t,{R:()=>c,x:()=>r});var i=n(6540);const s={},o=i.createContext(s);function c(e){const t=i.useContext(o);return i.useMemo((function(){return"function"==typeof e?e(t):{...t,...e}}),[t,e])}function r(e){let t;return t=e.disableParentContext?"function"==typeof e.components?e.components(s):e.components||s:c(e.components),i.createElement(o.Provider,{value:t},e.children)}}}]);